name: rtchat
description: RealtimeChat
publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  battery_plus: ^5.0.2
  audioplayers: ^6.0.0
  cloud_firestore: ^5.0.1
  cloud_functions: ^5.0.1
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_crashlytics: ^4.0.1
  firebase_database: ^11.0.1
  flutter_custom_tabs: ^1.2.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_localized_locales: ^2.0.5
  flutter_markdown: ^0.7.2+1
  flutter_tts: ^3.8.5
  flutter_web_auth: ^0.5.0
  google_fonts: ^4.0.4
  http: ^0.13.6
  in_app_purchase: ^3.2.0
  intl: ^0.19.0
  just_audio: ^0.9.39
  linkify: ^5.0.0
  metadata_fetch: ^0.4.1
  mobile_scanner: ^5.0.2
  motion_sensors:
    git:
      url: https://github.com/zesage/motion_sensors.git
      ref: master
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  streaming_shared_preferences: ^2.0.0
  sticky_headers: ^0.3.0+2
  styled_text: ^8.1.0
  url_launcher: ^6.3.0
  wakelock_plus: ^1.2.8
  webview_flutter: ^4.5.0
  webview_flutter_android: ^3.14.0
  webview_flutter_wkwebview: ^3.11.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/providers/
