name: rtchat
description: RealtimeChat
publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^4.1.0
  barcode_scan2: ^4.2.4
  characters: ^1.3.0
  cloud_firestore: ^4.13.6
  cloud_functions: ^4.5.8
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.7.4
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8
  firebase_database: ^10.3.8
  flutter_background_service: ^5.0.5
  flutter_custom_tabs: ^1.2.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_localized_locales: ^2.0.5
  flutter_markdown: ^0.6.18
  flutter_tts: ^3.8.5
  flutter_web_auth: ^0.5.0
  google_fonts: ^4.0.4
  google_mobile_ads: ^4.0.0
  http: ^0.13.6
  in_app_purchase: ^3.1.11
  intl: ^0.18.1
  just_audio: ^0.9.36
  linkify: ^5.0.0
  metadata_fetch: ^0.4.1
  motion_sensors:
    git: 
      url: https://github.com/zesage/motion_sensors.git
      ref: master
  package_info_plus: ^3.1.2
  path_provider: ^2.1.1
  provider: ^6.1.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.2
  streaming_shared_preferences: ^2.0.0
  sticky_headers: ^0.3.0+2
  styled_text: ^8.1.0
  url_launcher: ^6.2.2
  wakelock: ^0.6.2
  webview_flutter: ^4.4.1
  webview_flutter_android: ^3.13.1
  webview_flutter_wkwebview: ^3.10.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/providers/