name: rtchat
description: RealtimeChat
publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^4.1.0
  barcode_scan2: ^4.2.4
  characters: ^1.3.0
  cloud_firestore: ^4.8.3
  cloud_functions: ^4.3.4
  crypto: ^3.0.3
  cupertino_icons: ^1.0.5
  firebase_analytics: ^10.4.4
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_crashlytics: ^3.3.4
  firebase_database: ^10.2.4
  flutter_custom_tabs: ^1.0.4
  flutter_keyboard_visibility: ^5.4.1
  flutter_localized_locales: ^2.0.4
  flutter_markdown: ^0.6.17
  flutter_tts: ^3.7.0
  flutter_web_auth: ^0.5.0
  google_fonts: ^4.0.4
  google_mobile_ads: ^3.0.0
  http: ^0.13.6
  in_app_purchase: ^3.1.7
  intl: ^0.18.0
  just_audio: ^0.9.34
  linkify: ^5.0.0
  metadata_fetch: ^0.4.1
  motion_sensors: ^0.1.0
  package_info_plus: ^3.1.2
  path_provider: ^2.0.15
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  sticky_headers: ^0.3.0+2
  styled_text: ^7.0.0
  url_launcher: ^6.1.12
  wakelock: ^0.6.2
  webview_flutter: ^4.2.2
  webview_flutter_android: ^3.9.2
  webview_flutter_wkwebview: ^3.7.2

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/providers/