name: Deploy to Firebase on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $FIREBASE_ADMIN_SDK_SERVICE_ACCOUNT_JSON > functions/service_account.json
        env:
          FIREBASE_ADMIN_SDK_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_ADMIN_SDK_SERVICE_ACCOUNT_JSON }}
      - run: echo "TWITCH_CLIENT_ID=$TWITCH_CLIENT_ID\n" >> functions/.env
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      - run: echo "TWITCH_CLIENT_SECRET=$TWITCH_CLIENT_SECRET\n" >> functions/.env
        env:
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,firestore
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
